#!/bin/bash
if [ -z $MONITOR ]; then
  isInFile=$( xrandr --prop | grep -c "eDP-1")
  if [ $isInFile -eq 0 ]; then
    MONITOR="eDP1"
  else
    MONITOR="eDP-1"
  fi
fi

echo "MONITOR"
echo $MONITOR


BrightNow=`xrandr --verbose | grep Bright | head -1 | awk '{print $2}'`
echo "BrightNow"
echo $BrightNow

if ((`echo $BrightNow '=' 1.0 | bc`)); then
  BrightNew=1.1
else
  BrightNew=$(echo "$BrightNow + 0.1" | bc)
fi

echo "BrightNew: "
echo $BrightNew

xrandr --output $MONITOR --brightness $BrightNew
## this doesn't actually work yet.
